version: '3.8'

services:
  db:
    image: postgres:15.1
    hostname: auth
    container_name: auth-db
    restart: always
    ports:
      - 5435:5435
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=auth123
      - POSTGRES_DB=auth
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5435
    cap_add:
      - SYS_NICE # disables logs `mbind: Operation not permitted`
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'tarot-master']
      interval: 10s
      timeout: 5s
      retries: 5
